#!/bin/sh


case "$1" in
	start)
		/usr/bin/aagpio 17 18
		;;
	stop)
		killall aagpio
		;;
	restart|reload)
		killall aagpio
		/usr/bin/aagpio 17 18
	;;
	*)
 		echo "Usage: $0 {start|stop|restart}"
		exit 1
esac
exit $?
